(let ([a 1])
  (let ([b 2])
    (let ([c 3])
      (let ([d 4])
        (let ([e 5])
          (let ([f 6])
            (let ([g 7])
              (let ([h 8])
                (let ([i 9])
                  (let ([j 10])
                    (let ([k 11])
                      (let ([l (>= h 8)])
                        (let ([m (if (and l
                                          (< (read) 10))
                                     13
                                     14)])
                          (if (eq? m 13)
                              (+ a (+ b (+ (if (> c 3) 100 (read)) (+ d (+ e (+ f (+ g (+ h (+ i (+ j (+ k (- m (read)))))))))))))
                              (+ a (+ b (+ c (+ d (+ e (+ f (+ g (+ h (+ i (+ j (- k m)))))))))))))))))))))))))
