(let ([foo (let ([a (let ([b (let ([c (let ([d 9])
                                        (+ d 8))])
                               (let ([e (let ([f 10]) (+ f 1))])
                                 (+ (let ([x 1]) (+ x 15)) e))
                               )])
                      (+ b 6))])
             (+ a 5))])
  (+ foo 4))
